version: "3"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emumbaqor
      MYSQL_USER: d2s
      MYSQL_PASSWORD: d2s_1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_net

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5501:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DATABASE_URL: "mysql+pymysql://d2s:d2s_1234@db/emumbaqor"
    networks:
      - db_net

networks:
  db_net:
    driver: bridge

volumes:
  db_data:
