name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/dockerize'  # Run on push to dockerize branch
      - 'main'  # Run on push to the main branch (including merges)
  pull_request:
    branches:
      - 'main'  # Run on pull request to the main branch
      - 'feature/dockerize'  # Run on pull request to the dockerize branch

jobs:
  build-and-test:
    name: Build, Run Docker, and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker compose -f flaskapp/docker-compose.yml build

    - name: Start Docker containers
      run: |
        docker compose -f flaskapp/docker-compose.yml up -d  # Start in detached mode

    - name: Wait for service to be ready
      run: |
        # Adjust this sleep duration based on how long your app takes to start
        sleep 10

    - name: Set BASE_URL environment variable
      run: |
        echo "BASE_URL=https://0699-203-99-184-187.ngrok-free.app" >> $GITHUB_ENV


    - name: Run API tests with pytest
      run: |
        pip install -r flaskapp/requirements.txt
        pytest flaskapp/test.py --html=report.html

    - name: Send Email
      uses: hilarion5/send-mail@v1
      with:
        smtp-server: smtp.gmail.com
        smtp-port: 465
        smtp-secure: true
        from-email: zaema.khurram@emumba.com
        to-email: zaema.khurram@emumba.com
        username: zaema.khurram@emumba.com
        password: hzle msey pbno jwkl
        subject: Test Results
        body: |
          Test results are attached.
        content_type: text/html
        attachments: report.html

    - name: Stop Docker containers
      run: |
        docker compose -f flaskapp/docker-compose.yml down  # Stop and remove containers
